version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: learning-platform-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: learning_platform

  backend:
    build: ./backend
    container_name: learning-platform-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./client
    container_name: learning-platform-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
